#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */
# define _BASE 0
# define _UPPER 1
# define _LOWER 2

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_BASE] = LAYOUT_ergodox(KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_NO, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_NO, KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_NO, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_NO, KC_LALT, KC_LGUI, KC_SPC, KC_ESC, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_BSPC, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_EQL, KC_DEL, KC_CAPS, MO(_UPPER), KC_BSLS, MO(_LOWER)),
	[_UPPER] = LAYOUT_ergodox(KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_NO, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_NO, KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_NO, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_NO, KC_LALT, KC_LGUI, KC_SPC, KC_ESC, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_BSPC, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_EQL, KC_DEL, KC_CAPS, KC_TRNS, KC_BSLS, KC_NO), 
	[_LOWER] = LAYOUT_ergodox(KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_NO, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_NO, KC_LCTL, KC_A, KC_S, KC_D, KC_F, KC_G, KC_NO, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_NO, KC_LALT, KC_LGUI, KC_SPC, KC_ESC, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_BSPC, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_EQL, KC_DEL, KC_CAPS, KC_NO, KC_BSLS, KC_TRNS)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

#ifdef OLED_ENABLE

// ROTATE OLED 
oled_rotation_t oled_init_user(oled_rotation_t rotation) {
	return OLED_ROTATION_270;
}



// DRAW TO OLED 
// max is 5 characters horizontal, and 15 lines vertical
bool oled_task_user() {
	oled_set_cursor(0, 1);
	
	oled_write("LAYER", false);  //LINE 1
	
	//LINE 2 is this switch statement
	switch (get_highest_layer(layer_state)) {
		case _BASE:
			oled_write("  0  ", false);
			break;
		case _UPPER:
			oled_write("  1  ", false);
			break;
		case _LOWER:
			oled_write("  2  ", false);
			break;
		default:
			oled_write("ERROR", false);
	}
	
	oled_write("     ", false);	 //LINE 3
	oled_write("     ", false);  //LINE 4
	
	oled_write("CAPSL", false);  //LINE 5
	
	// THIS is LINE 6
	// Host Keyboard LED Status 
    led_t led_state = host_keyboard_led_state();
    //oled_write_P(led_state.num_lock ? PSTR("NUM ") : PSTR("    "), false);
    oled_write(led_state.caps_lock ? "> ON " : "> OFF", false);
    //oled_write_P(led_state.scroll_lock ? PSTR("SCR ") : PSTR("    "), false);
	
	
	
	//oled_write("> OFF", false);  //LINE 6
	
	
	oled_write("     ", false);  //LINE 7
	oled_write("STAT1", false);  //LINE 8
	oled_write("> 151", false);  //LINE 9
	oled_write("     ", false);  //LINE 10
	oled_write("STAT2", false);  //LINE 11
	oled_write("> 42 ", false);  //LINE 12
	oled_write("     ", false);  //LINE 13
	oled_write("STAT3", false);  //LINE 14
	oled_write("> 012", false);  //LINE 15
	return false;
}



#endif



