#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ergodox(KC_A, KC_6, KC_7, KC_8, KC_9, KC_0, KC_1, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_Q, KC_BSPC, KC_H, KC_J, KC_K, KC_L, KC_A, KC_SCLN, KC_RCTL, KC_N, KC_M, KC_COMM, KC_SLSH, KC_DOT, KC_Z, KC_RSFT, KC_BSPC, KC_LGUI, KC_SPC, KC_LALT)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)




